#Load the Data(PreProcess if needed)
#Param:
#     url : The path of Data
#
Load_Data = function(url){
  
  data = scan(url)
  
  return (data)
}

##Question 1
main_Question1 = function(){
  
  url = "http://www.mas.ncl.ac.uk/~nseg4/teaching/MAS8380/practical2.dat"
  data_PA = Load_Data(url)
  print(data_PA)
  
  mean_All = length(data_PA) %/% 12 # Get the mean of the Population
  
  num_Peo = (1:length(data_PA))
  mean_All = length(data_PA) / 12
  print(mean_All)
  
  plot(num_Peo,data_PA,main = '12 Hours Flow of Patients Arrival From 9am', xlab = 'The i-th Patient', ylab = 'Arrival Time of The i-th Patient ',col='red')
  legend("topleft", c("Each Arrival"),pch = c(1),col=c("red"),bg ="white")
  abline(a= 0, b = 1/mean_All)
  #abline(h = 1.3, col = 'red')
}

main_Question1()


#Question 2
main_Question2 = function(){
  
  url = "http://www.mas.ncl.ac.uk/~nseg4/teaching/MAS8380/practical2.dat"
  data_PA_2 = Load_Data(url) #Load the data
  
  interval = c(10,25,50,75,100,150) # Set the different interval
  interval_mean = c() # Store the mean for each interval method
  interval_var = c()  # Store the variance for each interval method
  lambda = c() # store the lambda for each interval
  count = 1 # count the index of vector above
  
  for (k_I in interval){ # Loop of the different ways of interval
    
    inte_num = table(cut(data_PA_2, breaks = k_I)) # The orders of data after cutting
    
    interval_mean[count] = mean(inte_num) # Mean for each interval method
    
    interval_var[count] = var(inte_num) # variance for each interval method
    
    count = count + 1 # Index to next element in vector
    
  }
  
  # Plot the mean versus variance in different ways of interval
  plot(interval_mean,interval_var,main = '12 Hours Flow of Patients Arrival From 9am', xlab = 'Mean of different methods of interval', ylab = 'Var of different methods of interval',type = 'l', col='red')
  #lines(interval,interval_var,type = "l")
  #legend("topright", c("Mean", "Var"),lty = c(1,1),col=c("red","black"),bg ="white")
}

main_Question2() # Run the Question2


#Question 3
#lambda : 
#       choose the lambda in Poisson distribution
#
Question3 = function(lambda){
  
    y_store = c() # store the each time generated by rexp
    t_store = c(1) # store the time of each patient
    count_times = 1# count the index of vector above
    
    while(t_store[length(t_store)] <= 12) { # Loop of the Time until it exceeds 12
      
      arrivals = rexp(1,lambda) # just generated the time follow exp randomly
      
      y_store[count_times] = arrivals # store the each time generated by rexp
      
      t_store[count_times] = cumsum(y_store)[length(y_store)]
      #Store the time of each patient's arrival
      
      count_times = count_times + 1 # Index to next element in vector
    }
    
    return (t_store) # Return the time we stored for each patient
}

main_Question3 = function(){
  
  lambda =10
  
  arr_times = Question3(10) # Get the arrival time
  
  num_Peo = (1:length(arr_times)) # Get the number of the people
  
  #Plot the of the time of the patients
  plot(num_Peo, arr_times ,main = '12 Hours Flow of Patients Arrival From 9am', xlab = 'The i-th Patient', ylab = 'Arrival Time of The i-th Patient ', col='red')
  abline(a= 0, b = 1/10) # Give the line about lambda to check
  legend("topleft", c("Each Arrival"),pch = c(1),col=c('red'),bg ="white")
}

main_Question3() # Run the Question3

